name: Deploy Vue App to Mijn.Host

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Clean Remote Directory
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        port: ${{ secrets.SFTP_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf /home/bp102530/domains/leesrisale.nl/public_html/*

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USER }}
        port: ${{ secrets.SFTP_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/**"
        target: "/home/bp102530/domains/leesrisale.nl/public_html/"
        strip_components: 1
